const mongoose = require("mongoose");

// =========================================================================
// deliveryData Model & Schema
// =========================================================================

let deliveryDataSchemaHA = new mongoose.Schema({
  ["Truck"]: String,
  ["Bill To Name"]: String,
  ["Ship To Name"]: String,
  ["Model"]: String,
  ["Order No"]: String,
  ["Line No"]: String,
  ["Order Type"]: String,
  ["Line Status"]: String,
  ["Hold Flag"]: String,
  ["Ready To Pick"]: String,
  ["Pick Released"]: String,
  ["Instock Flag"]: String,
  ["Order Qty"]: String,
  ["Unit Selling Price"]: String,
  ["Sales Amount"]: String,
  ["Tax Amount"]: String,
  ["Charge Amount"]: String,
  ["Line Total"]: String,
  ["List Price"]: String,
  ["Original List Price"]: String,
  ["DC Rate"]: String,
  ["Currency"]: String,
  ["DFI Applicable"]: String,
  ["AAI Applicable"]: String,
  ["Cancel Qty"]: String,
  ["Booked Date"]: String,
  ["Req Arrival Date From"]: String,
  ["Req Arrival Date To"]: String,
  ["Req Ship Date"]: String,
  ["Line Type"]: String,
  ["Customer Name"]: String,
  ["Bill To"]: String,
  ["Department"]: String,
  ["Ship To"]: String,
  ["Ship To Full Name"]: String,
  ["Store No"]: String,
  ["Price Condition"]: String,
  ["Payment Term"]: String,
  ["Customer PO No"]: String,
  ["Customer Po Date"]: String,
  ["Sales Person"]: String,
  ["Inventory Org"]: String,
  ["Sub- Inventory"]: String,
  ["Shipping Method"]: String,
  ["Order Source"]: String,
  ["Order Status"]: String,
  ["Order Category"]: String,
  ["Receiver City Desc"]: String,
  ["Receiver Postal code"]: String,
  ["Receiver State"]: String,
  ["Item Division"]: String,
  ["Product Level1 Name"]: String,
  ["Product Level2 Name"]: String,
  ["Product Level3 Name"]: String,
  ["Product Level4 Name"]: String,
  ["Product Level4 Code"]: String,
  ["Model Category"]: String,
  ["Item Type"]: String,
  ["Item Weight"]: String,
  ["Item CBM"]: String,
  ["Sales Channel (High)"]: String,
  ["Sales Channel (Low)"]: String,
  ["Back Order Hold"]: String,
  ["Credit Hold"]: String,
  ["Overdue Hold"]: String,
  ["Customer Hold"]: String,
  ["Payterm Term Hold"]: String,
  ["FP Hold"]: String,
  ["Minimum Hold"]: String,
  ["Future Hold"]: String,
  ["Reserve Hold"]: String,
  ["Manual Hold"]: String,
  ["Auto Pending Hold"]: String,
  ["S/A Hold"]: String,
  ["Form Hold"]: String,
  ["Bank Collateral Hold"]: String,
  ["Insurance Hold"]: String,
  ["Inventory Reserved"]: String,
  ["Pick Release Qty"]: String,
  ["SO-SA Mapping"]: String,
  ["Picking Remark"]: String,
  ["Shipping Remark"]: String,
  ["Create Employee Name"]: String,
  ["Create Date"]: String,
  ["Order Date"]: String,
  ["Customer RAD"]: String,
  ["Accounting Unit"]: String,
  ["Customer Model"]: String,
  ["CNPJ"]: String,
  ["SO Status(2)"]: String,
  ["SBP Tax Include"]: String,
  ["SBP Tax Exclude"]: String,
  ["RRP Tax Include"]: String,
  ["RRP Tax Exclude"]: String,
  ["SO FAP Flag"]: String,
  marked: Boolean,
  ["Slot Date"]: Date,
  ["Slot Time"]: Date,
  ["Reservation No"]: String,
  ["Status"]: String
});

module.exports = mongoose.model("ha-dd", deliveryDataSchemaHA);